services:
  db:
    container_name: authsrvdb
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=${AUTHSRV_DB_USERNAME}
      - POSTGRES_PASSWORD=${AUTHSRV_DB_PASSWORD}
      - POSTGRES_DB=${AUTHSRV_DB_DBNAME}
    ports:
      - '5432:5432'
    volumes:
      - authsrvdata:/var/lib/postgresql/data

  cache:
    container_name: authsrvcache
    image: 'redis:latest'
    command:
      --requirepass ${AUTHSRV_CACHE_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - cachedata:/data

volumes:
  authsrvdata:
  cachedata: