CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USERS(
    ID UUID DEFAULT uuid_generate_v4(),
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(200),
    PASSWORD_HASH VARCHAR(128) NOT NULL,
    IS_SUPERUSER BOOLEAN DEFAULT FALSE,
    FIRST_NAME VARCHAR(200),
    LAST_NAME VARCHAR(200),
    MIDDLE_NAME VARCHAR(200),
    PRIMARY KEY(ID)
);

CREATE TABLE SCOPES(
    ID UUID DEFAULT uuid_generate_v4(),
    NAME VARCHAR(200) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500),
    PRIMARY KEY(ID)
);

CREATE TABLE ROLES(
    ID UUID DEFAULT uuid_generate_v4(),
    NAME VARCHAR(200) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500),
    PRIMARY KEY(ID)
);

CREATE TABLE ROLES_SCOPES(
    ROLE_ID UUID NOT NULL,
    SCOPE_ID UUID NOT NULL,
    PRIMARY KEY(ROLE_ID, SCOPE_ID),
    CONSTRAINT FK_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID),
    CONSTRAINT FK_SCOPE FOREIGN KEY(SCOPE_ID) REFERENCES SCOPES(ID)
);

CREATE TABLE USER_ROLES(
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    PRIMARY KEY(USER_ID, ROLE_ID),
    CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID)
);