CREATE VIEW ROLES_SCOPES_DETAILS
    AS SELECT RS.ROLE_ID AS ROLE_ID,
              RS.SCOPE_ID AS SCOPE_ID,
              SC.NAME AS SCOPE_NAME
    FROM ROLES_SCOPES AS RS
    INNER JOIN SCOPES AS SC ON SC.ID = RS.SCOPE_ID;

CREATE VIEW USERS_ROLES_DETAILS
    AS SELECT UR.USER_ID AS USER_ID,
              RL.ID      AS ROLE_ID,
              RL.NAME    AS ROLE_NAME
    FROM USER_ROLES AS UR
    INNER JOIN ROLES AS RL ON UR.ROLE_ID = RL.ID;

CREATE VIEW USER_AUTH
    AS SELECT URD.USER_ID AS USER_ID,
              URD.ROLE_ID AS ROLE_ID,
              URD.ROLE_NAME AS ROLE_NAME,
              RSD.SCOPE_ID AS SCOPE_ID,
              RSD.SCOPE_NAME AS SCOPE_NAME
    FROM USERS_ROLES_DETAILS AS URD
    LEFT JOIN ROLES_SCOPES_DETAILS AS RSD ON URD.ROLE_ID = RSD.ROLE_ID;